### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Answordy** [Stardust-Labs-MC/alex-mobs-configs#1]
Starting from line 52...

cave/crystal_caves = forBiomes("terralith:cave/crystal_caves")
bryce_canyon.addDicTypes("UNDERGROUND", "MAGICAL", "OVERWORLD")

cave/deep_caves = forBiomes("terralith:cave/deep_caves")
bryce_canyon.addDicTypes("UNDERGROUND", "OVERWORLD")

should be...

cave/crystal_caves = forBiomes("terralith:cave/crystal_caves")
cave/crystal_caves.addDicTypes("UNDERGROUND", "MAGICAL", "OVERWORLD")

cave/deep_caves = forBiomes("terralith:cave/deep_caves")
cave/deep_caves.addDicTypes("UNDERGROUND", "OVERWORLD")

**Comment by catter1** [comment]
Biomes removed, no longer an issue
